# Site settings
title: Jianqiao's Blog
email: camb.zhu@gmail.com
description: ""
baseurl: ""
url: "http://camzhu.github.io"
twitter_username: JQ_Zhu
github_username:  camzhu
weibo_username: cambridgezhu

# Build settings
markdown: redcarpet
permalink: pretty
