# Site settings
title: Jianqiao Zhu
email: camb.zhu@gmail.com
description: ""
baseurl: ""
url: "http://jianqiaozhu.github.io"
twitter_username: JQ_Zhu
github_username:  jianqiaozhu
weibo_username: cambridgezhu

# Build settings
markdown: kramdown
permalink: pretty
