# Site settings
title: Jianqiao's Blog
email: camb.zhu@gmail.com
description: "Data Science."
baseurl: ""
url: "http://camzhu.github.io"
twitter_username: JQ_Zhu
github_username:  camzhu

# Build settings
markdown: redcarpet
permalink: pretty
